language: objective-c
osx_image: xcode10.1
xcode_workspace: WeatherDay.xcworkspace
xcode_scheme: WeatherDay
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - bundle install
  - bundle exec pod install --repo-update
install:
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
script:
  - ./scripts/linter
